Repository Breakthrough-Energy/PowerSimData, pull requests merged in 2021-09, with the labels that each got.

#536 docs: update README to signal package availability on PyPi
  README.md
Labels: documentation

#544 fix: access column values instead of DataFrame method
  powersimdata/design/investment/investment_costs.py
Labels: bug

#546 fix: correct generation of duplicated bus entries in bus-to-NEEM-region mapping
  powersimdata/design/investment/create_mapping_files.py
  powersimdata/design/investment/data/buses_NEEMregion.csv
Labels: bug

#553 Remove psycopg2 dependency
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  Pipfile
  Pipfile.lock
  powersimdata/data_access/tests/sql/test_execute_table.py
  powersimdata/data_access/tests/sql/test_scenario_table.py
  powersimdata/data_access/tests/sql/test_sql_store.py
  pytest.ini
  tox.ini
Labels: dependencies
