Repository Breakthrough-Energy/PowerSimData, pull requests merged in 2021-03, with the labels that each got.

#405 Modify schema of scenario list
  powersimdata/data_access/scenario_list.py
  powersimdata/data_access/sql/schema.sql
  powersimdata/data_access/tests/test_scenario_csv.py
  powersimdata/data_access/tests/test_scenario_table.py
  powersimdata/utility/templates/ScenarioList.csv
Labels: feature request

#408 Update code snippet of README
  README.md
Labels: documentation

#409 Refactor mock objects
  powersimdata/tests/mock_grid.py
  powersimdata/tests/mock_scenario.py
Labels: grid, refactor

#411 fix/refactor: return grid model for ScenarioGrid, reduce repeated get_grid_model calls
  powersimdata/design/generation/clean_capacity_scaling.py
  powersimdata/design/transmission/upgrade.py
  powersimdata/input/grid.py
Labels: bug

#416 Manage scenario/execute list using pandas
  powersimdata/data_access/csv_store.py
  powersimdata/data_access/data_access.py
  powersimdata/data_access/execute_list.py
  powersimdata/data_access/scenario_list.py
  powersimdata/data_access/tests/test_execute_csv.py
  powersimdata/data_access/tests/test_execute_table.py
  powersimdata/data_access/tests/test_scenario_csv.py
  powersimdata/data_access/tests/test_scenario_table.py
  powersimdata/scenario/delete.py
  powersimdata/scenario/execute.py
  powersimdata/scenario/move.py
  powersimdata/utility/server_setup.py
  powersimdata/utility/templates/__init__.py
  setup.py
Labels: refactor

#422 fix: ensure that get_bus_demand works in Create state
  powersimdata/input/input_data.py
  powersimdata/scenario/create.py
  powersimdata/scenario/tests/test_create.py
Labels: bug

#427 fix: upload storage matfile to server
  powersimdata/scenario/execute.py
Labels: bug

#424 docs: fix and improve docstrings
  powersimdata/design/investment/create_mapping_files.py
  powersimdata/design/investment/investment_costs.py
  powersimdata/scenario/analyze.py
  powersimdata/scenario/create.py
Labels: documentation
