Repository Breakthrough-Energy/PowerSimData, pull requests merged in 2021-04, with the labels that each got.

#437 docs: improve docstring of Grid class
  powersimdata/input/grid.py
Labels: documentation

#432 Rewrite README
  README.md
  docs/capacity_planning.rst
  docs/grid.rst
  docs/index.rst
  docs/scenario.rst
  docs/scenario_design.rst
Labels: documentation

#429 Reduce chance of concurrency issues
  powersimdata/data_access/csv_store.py
  powersimdata/data_access/data_access.py
  powersimdata/data_access/execute_list.py
  powersimdata/data_access/profile_helper.py
  powersimdata/data_access/scenario_list.py
  powersimdata/data_access/tests/test_scenario_csv.py
  powersimdata/scenario/create.py
Labels: bug

#449 fix: close temp file before trying to move/delete
  powersimdata/data_access/csv_store.py
  powersimdata/data_access/data_access.py
Labels: bug

#450 fix: ensure that per-element investment cost are calculated accurately
  powersimdata/design/investment/investment_costs.py
  powersimdata/design/investment/tests/test_investment_costs.py
  powersimdata/input/change_table.py
  powersimdata/tests/mock_grid.py
Labels: bug

#462 fix: enable AC investment costs to be calculated for branches connected to new buses
  powersimdata/design/investment/investment_costs.py
Labels: bug

#463 feat: improve flexibility of MW-miles calculation, for Create state and new branches
  powersimdata/design/transmission/mwmiles.py
  powersimdata/design/transmission/tests/test_mwmiles.py
  powersimdata/scenario/create.py
  powersimdata/scenario/scenario.py
Labels: new feature

#465 doc/refactor: improve documentation and usability of investment costs
  powersimdata/design/investment/investment_costs.py
  powersimdata/design/investment/tests/test_investment_costs.py
  powersimdata/design/transmission/upgrade.py
Labels: documentation, refactor

#466 feat: allow scaling of added elements
  powersimdata/input/change_table.py
  powersimdata/input/tests/test_transform_grid.py
  powersimdata/input/transform_grid.py
Labels: new feature

#471 Add coverage report to pytest
  .coveragerc
  .github/workflows/test.yml
  Pipfile
  Pipfile.lock
  pytest.ini
  requirements.txt
  tox.ini
Labels: dependencies
