Repository Breakthrough-Energy/PowerSimData, pull requests merged in 2021-06, with the labels that each got.

#504 Josephine/calculate interzone capacity
  powersimdata/design/transmission/zones.py
Labels: new feature

#506 feat: add base_grid input to investment cost calculation functions
  powersimdata/design/investment/investment_costs.py
  powersimdata/input/check.py
  powersimdata/input/tests/test_check.py
Labels: new feature

#507 refactor: add compare module, move Grid/Scenario check functions from PostREISE to PowerSimData
  powersimdata/design/compare/__init__.py
  powersimdata/design/compare/generation.py
  powersimdata/design/compare/helpers.py
  powersimdata/design/compare/transmission.py
  powersimdata/design/investment/investment_costs.py
  powersimdata/input/check.py
  powersimdata/input/tests/test_check.py
  powersimdata/scenario/check.py
  powersimdata/scenario/tests/test_check.py
Labels: refactor

#515 doc: add docstring for kind param in export_transformed_profile
  powersimdata/input/export_data.py
Labels: documentation
