Repository Breakthrough-Energy/PowerSimData, pull requests merged in 2022-05, with the labels that each got.

#626 Aggregate demand profiles during scenario preparation
  powersimdata/input/tests/test_transform_demand.py
  powersimdata/input/transform_demand.py
  powersimdata/input/transform_profile.py
Labels: new feature

#629 Combine scenario list from different sources
  powersimdata/data_access/csv_store.py
  powersimdata/data_access/data_access.py
  powersimdata/scenario/execute.py
Labels: bug

#634 Relocate functions exporting data
  powersimdata/export/__init__.py
  powersimdata/export/export_scenario_inputs.py
  powersimdata/export/export_to_pypsa.py
  powersimdata/export/tests/test_export_to_pypsa.py
  powersimdata/scenario/execute.py
Labels: refactor

#639 fix: pin fs version to avoid regression in latest
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: dependencies
