Repository Breakthrough-Energy/PowerSimData, pull requests merged in 2022-09, with the labels that each got.

#656 Generalize generator types
  powersimdata/design/generation/clean_capacity_scaling.py
  powersimdata/design/generation/curtailment.py
  powersimdata/design/generation/tests/test_curtailment.py
  powersimdata/design/transmission/upgrade.py
  powersimdata/input/change_table.py
  powersimdata/input/changes/plant.py
  powersimdata/input/tests/test_check.py
  powersimdata/input/transform_grid.py
  powersimdata/input/transform_profile.py
  powersimdata/network/constants/color.py
  powersimdata/network/constants/efficiency.py
  powersimdata/network/constants/emission.py
  powersimdata/network/constants/label.py
  powersimdata/network/constants/plants.py
  powersimdata/network/constants/resource.py
  powersimdata/scenario/ready.py
Labels: refactor

#681 Fix resource name resource name
  powersimdata/network/constants/resource.py
Labels: bug

#679 add data structure for expansion candidates
  powersimdata/input/expansion_candidates.py
  powersimdata/input/tests/test_expansion_candidates.py
Labels: CEM
